import 'package:flutter_riverpod/flutter_riverpod.dart';

final darkMode = StateProvider<bool>((ref) => true);
final infiniteMode = StateProvider<bool>((ref) => false);

//  double digbyX = 0;
//   double digbyY = 1;
//   double digbySize = 0.4;
//   double creatineX = 0.5;
//   double creatineY = 1;
//   double creatineSize = 0.35;
//   double snakeOilX = -0.5;
//   double snakeOilY = 1;
//   double snakeOilSize = 0.35;
//   bool snakeOilConsumed = false;
//   double senzuX = 30;
//   double senzuY = 1;
//   double senzuSize = 0.35;
//   double time = 0;
//   double height = 0;
//   double initialHeight = digbyY;
//   String direction = 'right';
//   double gravity = -4.9;
//   double velocity = 6;
//   bool movement = false;
//   bool midJump = false;
//   var gameFont = const TextStyle(color: Colors.white, fontSize: 20);
//   int score = 0;
//   final highScoreBox = Hive.box('highscore');
//   HighScore db = HighScore();
//   bool gameHasStarted = false;
//   double gameSpeed = 0.02;
//   int lives = 3;
//   Color backgroundColour = Colors.black;
//   static List<double> barrierX = [2, 3.5, 5, 6.5, 8, 9.5];
//   static double barrierWidth = 0.1;
//   List<double> barrierHeight = [0.6, 0.5, 0.8, 0.3, 1.2, 0.2];
//   List<bool> isGoblin = [false, false, false, false, true, false];
//   bool gameModeInfinite = false;
//   bool goblinMove = true;
